#+TITLE: emacs 配置

* 概述

这是我在使用 eamcs 过程中根据自己需求对 emacs 的配置。

我的系统是 Gentoo ，eamcs 版本是 emacs-vcs 27.0.9999。

大半年没更新，以下内容需要修改。

1) USE="X acl alsa cairo dynamic-loading gif gmp gpm imagemagick inotify jpeg lcms libxml2 motif png sound ssl svg threads tiff wide-int xft xpm zlib -Xaw3d (-aqua) -athena -dbus -games -gconf -gfile -gsettings -gtk -gtk2 -gzip-el -harfbuzz -json -kerberos -livecd -m17n-lib -mailutils (-selinux) -source -systemd -toolkit-scroll-bars -xwidgets" ABI_X86="(64)"
2) dynamic-loading 使得 emacs 可以加载 .so 文件（fuz.el）。此外，emacs-27 使用 XDG 作为配置目录。
   即，原 ~/.emacs.d/init.el 变成 ~/.config/init.el
3) 使用 submodule 来管理插件，所有插件安装目录为 site-lisp，具体各个目录作用：
   1) site-lisp/libs：插件所用的信赖包
   2) emacs-gnu-elpa：从 elpa 上下载来的
   3) 其他：插件
4) 使用插件 exwm（[[https://github.com/ch11ng][ch11ng]]）作为 WM。对于 exwm 来讲，使用 exim 才能正常使用 emacs 的输入法。目前 exwm 内置了 exim。
   之前尝试过 emacs-leim-extra 配合挺好（其他没尝试，习惯五笔）。之前 pyim 对于 X11 应用效果不好，但是目前对此进行了改进，
   因此目前使用的输入法方案为：pyim + pyim-wbdict。

* 目录结构

主要文件：

#+BEGIN_SRC sh
.
├── init.el                       # Emacs 从这个文件开始执行
└── lisp                          # 各个（插件）配置文件，以下内容需要修改
    ├── init-better.el            # 与插件无关的配置
    ├── init-company.el           # 与自动补全 company 相关
    ├── init-exwm.el              # wm
    ├── init-ggtags.el            # 代码浏览
    ├── init-im.el                # 输入法
    ├── init-lsp.el               # lsp mode
    ├── init-multiple-cursors.el  # 多行编辑
    ├── init-org.el               # org-mode 配置 // emacs 26.1_rc1 对这个配置会报错，暂时不用
    ├── init-sly.el               # sly 相关
    ├── init-smex.el              # smex 相关
    └── init-yasnippet.el         # yasnippet 相关
└── site-lisp                     # submodule 管理的各个插件
    ├── emacs-gnu-epla            # elpa 上下载的包
    ├── libs                      # 插件信赖的包
    └── submodule                 # 指代一系列目录，各个插件
#+END_SRC

* 插件

| 插件                 | 功能                   |
|----------------------+------------------------|
| company              | 自动补全框架           |
| company-auctex       | LaTeX 补全后端         |
| company-c-headers    | C 头文件补全           |
| slime-company        | slime 补全后端         |
| yasnippet            | 模板系统               |
| common-lisp-snippet  | common lisp 的模板     |
| sly（替换原先slime） | lisp 交互模式          |
| multiple-cursors     | 多行编辑               |
| smex                 | M-x 模糊匹配           |
| window-numbering     | 跳转子窗口             |
| exwm                 | wm                     |
| fcitx                | 使输入法更好用         |
| ggtags               | 更好的浏览代码         |
| yasnippet-snippets   | snippet 模板           |
| xelb                 | 支持 exwm              |
| exim                 | 支持 exwm 下中文输入   |
| emacs-leim-extra     | 五笔输入法             |
| pdf-tools            | PDF 工具，DocView 替代 |
| lsp-mode             | lsp                    |
| pyim                 | 输入法                 |
| pyim                 | pyim 输入法五笔        |


* 说明

* 之后计划

***** TODO [-] 完成所有 submodule 下载和配置

***** TODO [-] 移动网络下 github/ssh 高效下载配置

* 问题
