export XMODIFIERS=@im=ibus
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export QT4_IM_MODULE=ibus
ibus-daemon -drx
#emacsclient -a "" -e "(require 'init-exwm)"
exec emacs --eval="(require 'init-exwm)"
